insert into user_details(id, birth_date, name) values(10001, current_date(), 'Ranga');
insert into user_details(id, birth_date, name) values(10002, current_date(), 'Ravi');
insert into user_details(id, birth_date, name) values(10003, current_date(), 'Satish');
insert into user_details(id, birth_date, name) values(10004, current_date(), 'Raghu');
insert into user_details(id, birth_date, name) values(10005, current_date(), 'Rahul');
insert into user_details(id, birth_date, name) values(10006, current_date(), 'Rajesh');
insert into user_details(id, birth_date, name) values(10007, current_date(), 'Ramesh');
insert into user_details(id, birth_date, name) values(10008, current_date(), 'Rakesh');
insert into user_details(id, birth_date, name) values(10009, current_date(), 'Raj');